version: '3'

volumes:
  wp_vol:
    driver: local
    name: wp_vol
    driver_opts:
      type: none
      o: bind
      device: /home/mchau/data/wp_vol #todo  исправить после переноса на ВМ и создать там, шоб все было как в subject - /home/mchau/data/wp_vol
  db_vol:
    driver: local
    name: db_vol
    driver_opts:
      type: none
      o: bind
      device: /home/mchau/data/db_vol #todo  исправить после переноса на ВМ и создать там, шоб все было как в subject - /home/mchau/data/db_vol

networks:
  mchau_network:
    name: mchau_network
    driver: bridge

services:
  nginx:
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    env_file: .env
    image: nginx
    restart: always
    user: root
    container_name: nginx
    networks:
      - mchau_network
    ports:
      - "443:443"
    volumes:
      - wp_vol:/var/www/html
  wordpress:
    env_file: .env
    build:
      context: ./requirements/wordpress
      args:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
    image:  wordpress
    restart: always
    user: root
    container_name:  wordpress
    networks:
      - mchau_network
    volumes:
      - wp_vol:/var/www/html
  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_USER_PASSWORD=${MYSQL_USER_PASSWORD}
    env_file: .env
    image: mariadb
    restart: always
    user: root
    container_name: mariadb
    networks:
      - mchau_network
#   volumes:
#      - db_vol:/var/lib/mysql
