VAR = '$(docker ps -a -q)'

all:
	docker-compose -f ./srcs/docker-compose.yml up --build -d

stop:
	docker-compose -f ./srcs/docker-compose.yml down



# mysql -u root -p
# show databases;
# use mchau;
# show tables;
# select * from ... ;
# exit
