#!/bin/bash
#test it!
echo "---Start testing:----"
cd ../ && make && cd TESTER
gcc -Wall -Wextra -Werror main.c -L../ -lftprintf -I../
> user_printf_output
./a.out > user_printf_output
echo "---DIFFs:----"
diff system_printf_output user_printf_output
