#!/bin/bash
#test it!
clear
echo "---Start testing:---"
cd ../ && make re && cd TESTER
gcc -Wall -Wextra -Werror main.c -L../ -lftprintf -I../includes
> user_printf_output
./a.out > user_printf_output
echo "---DIFFs:----"
#cat system_printf_output
#echo '---versus---'
#cat user_printf_output
diff -c  system_printf_output user_printf_output
